from typing import Any

ErrorType = str

class Raiser:
    def __init__(cls, msg: ErrorType): ...
    def Raise(cls): ...
    def __str__(cls) -> ErrorType: ...
    def __repr__(cls) -> ErrorType: ...

class Error:
    __sep__ = " "

    def __init__(self, *args: Any, **kwds: Any): ...
    @property
    def name(self): ...
    @name.setter
    def name(self, name: str): ...
    @property
    def sep(self): ...
    @sep.setter
    def sep(self, sep: str): ...
    def __str__(self) -> ErrorType: ...
    def __repr__(self) -> ErrorType: ...

def error(*args: Any, **kwds: Any): ...
